### ISSUE TITLE
Running locally didn't work for me

### ISSUE THREAD

**Issue by JohnMarsing** [anthonychu/blazor-auth-static-web-apps#1]
Hello Anthony,

I followed the instructions on your [blog](https://anthonychu.ca/post/blazor-auth-azure-static-web-apps/) and I couldn't log in locally.  When I published it and tried to login it worked.

After clicking the login page (https://localhost:5001/login-providers) and clicking the **Sign in with Github** link it returns to https://localhost:5001/.auth/login/github and says **Sorry, there's nothing at this address.**

Here's my Blazor Azure Static WebApp [GitHub](https://github.com/JohnMarsing/TorahGatedCommunity) page.

Anyway, thanks for the blog.  Looking forward to when **Azure Static Web Apps** (ASWA) will have native support for **Blazor** and also when ASWA supports **Azure Function** using c#.

Thanks
John Marsing

**Comment by anthonychu** [comment]
It only works when deployed. There isn’t a great way to test auth locally right now. C# functions as well as native building of Blazor apps are coming soon. Being able to use auth locally is going to be a bit further out.

**Comment by JohnMarsing** [comment]
thanks,
