### ISSUE TITLE
Running the app locally

### ISSUE THREAD

**Issue by myaesubi** [anthonychu/blazor-auth-static-web-apps#4]
Hi @anthonychu,
Thank you for the sample, it really helped me to get auth/authz  working.

my question is how I can get to test the app locally. When I put the auth/authz in place, there no way that I can test it locally before push the code to github so to kick off CI/CD pipeline.

Thanks,
Mohammad

**Comment by Zhiyuan-Amos** [comment]
@myaesubi take a look at https://github.com/anthonychu/blazor-auth-static-web-apps/issues/1

**Comment by myaesubi** [comment]
Thanks. got it.
